Repository OSCA-Kampala-Chapter/autobot, pull requests merged in 2022-11, with the labels that each got.

#107 Docs: GitHub pages deployment
  .github/workflows/ci.yml
Labels: documentation

#129 add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr-new-feature

#150 made api methods async and replaced api methods' properties with keyward arguments.
  autobot/telegram/api.py
Labels: enhancement
